import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/organisms/Navbar';
import Footer from '@/components/organisms/Footer';
import PrivacyPolicy from '@/components/organisms/PrivacyPolicy';
import { QueryProvider } from '@/components/providers/QueryProvider';
import { Toaster } from 'sonner';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'LSCS App',
    description: 'Generated by LSCS Next.js App',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="flex flex-col min-h-screen">
                    <Navbar />
                    <QueryProvider>
                        <main className="flex flex-col grow">{children}</main>
                    </QueryProvider>
                    <PrivacyPolicy />
                    <Toaster position='top-center'/>
                </div>
                <Footer />
            </body>
        </html>
    );
}